### PR TITLE
2.9

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
For #37 

I fixed a test and added the new rules.
Do you want me to convert all rules to new string syntax or do you prefer the numbers?
Also do you want me to include tests for the new rules?

### CODE REVIEW

**Comment by cjihrig** [comment]
> Do you want me to convert all rules to new string syntax or do you prefer the numbers?

If you wouldn't mind, that would be great. Whichever route we go, we should be consistent though.

> Also do you want me to include tests for the new rules?

Yes, please.

**Comment by AdriVanHoudt** [comment]
@cjihrig I did see that eslint docs do not prefer string over number just states "'error' or 2" so...

**Comment by cjihrig** [comment]
IMO strings are more developer friendly.

**Comment by AdriVanHoudt** [comment]
@cjihrig  1 test error https://travis-ci.org/continuationlabs/eslint-config-hapi/jobs/127603105#L219 not sure what happened. I can update the travis to also include v6? and maybe remove the old iojs's?

**Comment by cjihrig** [comment]
Wow, don't see segmentation faults every day. Yea, we only need to support 4, 5, and 6.

**Comment by AdriVanHoudt** [comment]
@cjihrig all green now 🎉

**Comment by cjihrig** [comment]
Awesome. Thank you!

**Pull request merged**
